version: "3.7"

services:
  backend:
    build: ./code-belt3
      args:
        JAR_FILE: /spring-boot-cassandra-0.0.1-SNAPSHOT.jar
    depends_on:
      - cassandradb   
    networks:
      - network-backend
      - network-frontend

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://api:9003/data
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - network-frontend

  cassandradb:
    image: cassandra:3.11.8
    container_name: cassandra1
    ports:
      - "9042:9042"  
    networks:
     - network-backend
     
  networks:
  network-backend:
  network-frontend:

