version: "3.7"

services:
  backend:
    build: ./code-belt3
    depends_on:
      - cassandradb
	  args:
        JAR_FILE: /spring-boot-cassandra-0.0.1-SNAPSHOT.jar   
    networks:
      - network-backend
      - network-frontend

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://api:9003/data
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-frontend

  cassandradb:
    image: cassandra:3.11.8
	container_name: cass1
    hostname: cass1
	 ports:
      - "9042:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./data/cass1:/var/lib/cassandra    # This is the volume that will persist data for cassandra node
      - ./etc/cass1:/etc/cassandra   # Use your own config files for full control
	  
	  
	  
    networks:
      - network-backend
